# An arbitrary number of punishments may be defined.
# The internal name is used for tab-completing and the display-name for GUI.
# The type can either be "BAN" or "MUTE" depending on the type of punishment to deal.
# Durations are listed in hours.
punishments:
  xray-1d:
    internal-name: "Xray"
    display-name: "&cXray Ban"
    material: "DIAMOND_ORE"
    type: "BAN"
    durations:
      - 24
      - 72
      - 168
      - 744
      - 8928

# These are reasons that a player may wish to report another player.
# Players will also be allowed to type in their own reason.
reasons:
  - "flight"
  - "xray"
  - "KAura"
  - "Reach"

# Whether to use the listed integration.
hooks:
  # LiteBans can be used to issue punishments as an alternative to the built-in system.
  lite-bans: true